import React from 'react';
import Marquee from 'react-fast-marquee';
import './StoreGallery.css';

export default function StoreGallery() {
    // Array of the optimized image filenames generated by our script
    const images = [
        'img1.webp', 'img5.webp', 'img6.webp', 'img7.webp', 'img9.webp', 
        'img10.webp', 'img11.webp', 'img13.webp', 'img14.webp', 'img15.webp', 
        'img16.webp', 'img17.webp', 'img18.webp', 'img19.webp', 'img23.webp', 
        'img25.webp', 'img26.webp', 'img27.webp', 'img28.webp', 'img29.webp', 
        'img30.webp', 'img31.webp', 'img32.webp'
    ];

    // Split into two rows for a more dynamic look
    const row1 = images.slice(0, 11);
    const row2 = images.slice(11);

    return (
        <section className="store-gallery-section section">
            <div className="container">
                <div className="section-header-row" style={{ textAlign: 'center', display: 'block', marginBottom: '2rem' }}>
                    <h2 className="section-title" style={{ fontSize: '2rem' }}>🏪 Take a Look Inside</h2>
                    <p className="section-subtitle">Real photos of our aisles, fresh produce, and fully stocked shelves in Haldwani.</p>
                </div>
            </div>

            <div className="marquee-container">
                <Marquee speed={40} gradient={true} gradientColor={[249, 250, 251]} pauseOnHover={true}>
                    {row1.map((img, idx) => (
                        <div key={`row1-${idx}`} className="gallery-img-wrapper">
                            <img src={`/store-gallery/${img}`} alt={`Pandey Grocery Store Aisle ${idx + 1}`} loading="lazy" />
                        </div>
                    ))}
                </Marquee>
                
                <div style={{ height: '16px' }}></div>
                
                <Marquee speed={35} direction="right" gradient={true} gradientColor={[249, 250, 251]} pauseOnHover={true}>
                    {row2.map((img, idx) => (
                        <div key={`row2-${idx}`} className="gallery-img-wrapper">
                            <img src={`/store-gallery/${img}`} alt={`Pandey Grocery Store Produce ${idx + 1}`} loading="lazy" />
                        </div>
                    ))}
                </Marquee>
            </div>
        </section>
    );
}
